//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otel_Rezervasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iletisim
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public int MusteriID { get; set; }
    
        public virtual Musteri Musteri { get; set; }
    }
}
